name: Deploy Angular to Amazon S3

on:
  push:
    branches:
      - master  # Desplegará cada vez que hagas push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

      # 5. Configurar credenciales AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} #

      # 6. Sincronizar archivos al bucket S3
      - name: Deploy to S3
        run: aws s3 sync dist/pokemon-ssr s3://${{ secrets.S3_BUCKET }} --delete
